### ISSUE TITLE
Information discarded by bindgen which we need (tracker bug)

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#124]
bindgen doesn't pass on _quite_ all the information we need in order to be able to generate autocxx bindings. Options in the future might be to fork bindgen, ask _very_ nicely if they mind us upstreaming patches to add metadata, or switch away from bindgen and use llvm directly.

In any case this bug will be a live tracker of all known cases where we don't have all the information that we require about the underlying C++.

- [ ] **Classes vs structs**. Both present as `struct`s in the bindgen output. When we then generate extra C++ we have to plump for one or the other. In some ABIs this will result in a binary incompatibility or failure to compile.
- [ ] **Overloaded methods vs methods ending in digits.** Two methods `a(uint32_t)` and `a(uint8_t)` will be output as `a` and `a1`. There is no way for us to distinguish that from methods really called `a` and `a1`. Worse, this is across all the types in a namespace, so `MyStruct::a` and `MyOtherStruct::a` become `MyStruct::a` and `MyOtherStruct::a1`.
- [ ] **Nested types**. A `struct` nested inside another `struct` is not noted in the bindgen output, so we can't generate compatible C++ code - #115.

**Comment by martinboehme** [comment]
> * [ ]  **Classes vs structs**. Both present as `struct`s in the bindgen output. When we then generate extra C++ we have to plump for one or the other. In some ABIs this will result in a binary incompatibility or failure to compile.

Not sure I understand -- I always thought a struct was exactly identical to a class, just that it has public visibility by default? And I _believe_ it's legal for forward declarations of a `struct` to use `class` and vice versa (see [this StackOverflow answer](https://stackoverflow.com/a/40738415)). I'm pretty sure there isn't an ABI difference either. Or am I misunderstanding what you're referring to here?

**Comment by adetaylor** [comment]
This is #54 - let's discuss over there.

**Comment by martinboehme** [comment]
Thanks for the clarification -- interesting!

**Comment by adetaylor** [comment]
For #414 and #102 many types have 'annotations' attached (the `RustTy` type in our fork of bindgen). Such annotations are currently discarded using an `ignore_annotations` method. Each time that happens, it's probably a bug. For example this means we would try (and fail) to generate POD struct fields using types with template parameters which `bindgen` has dropped. Once a plan presents itself here, we should ensure we never drop information like this.

**Comment by martinboehme** [comment]
Note from https://github.com/google/autocxx/issues/426: The Rust function signature for copy constructors and move constructors is the same, so bindgen needs to add an annotation that allows us to distinguish between them.

**Comment by bsilver8192** [comment]
#799 is also on this list, and I'm pretty sure #815 is too.

**Comment by adetaylor** [comment]
I'm working on this.

Until I started on this:
Fork was 1444 insertions, 662 deletions.
It's now only 1179 insertions, 524 deletions.

Bits I'm going to _try_ to upstream:
* `char16_t` support https://github.com/rust-lang/rust-bindgen/pull/3135
* Add extra tests https://github.com/rust-lang/rust-bindgen/pull/3134
* Report enums in callbacks https://github.com/rust-lang/rust-bindgen/pull/3133
* Discovery callbacks for functions, methods
* Discovery callbacks for mods; plus provide enough C++ name information to identify the active namespace of each item
* Anounce when C++ name differs due to nested types
* Callbacks with C++ information - virtualness, explicitness, special memberness, C++ visibility
* Callback with original source code location
* Callback with structure layout
* Mark opaque types
* Mark C++ references
* Mark types with unused template params
* Callback for structs with unused template params
* Option to represent C++ operators
* Option to represent private and deleted functions
* Option to provide a specific virtual function receiver type
